// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account" | "/appointments" | "/cart" | "/category/[slug]" | "/checkout" | "/coming-soon/[department]" | "/contact-support" | "/faqs" | "/forgot-password" | "/heritage" | "/kids" | "/login" | "/men" | "/order-success" | "/order-tracking" | "/payment-failure" | "/privacy-policy" | "/product/[slug]" | "/reset-password" | "/returns-refund-policy" | "/search" | "/shipping-policy" | "/signup" | "/stores" | "/terms-and-conditions" | "/women"
type AppRouteHandlerRoutes = "/images/[...path]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/account": {}
  "/appointments": {}
  "/cart": {}
  "/category/[slug]": { "slug": string; }
  "/checkout": {}
  "/coming-soon/[department]": { "department": string; }
  "/contact-support": {}
  "/faqs": {}
  "/forgot-password": {}
  "/heritage": {}
  "/images/[...path]": { "path": string[]; }
  "/kids": {}
  "/login": {}
  "/men": {}
  "/order-success": {}
  "/order-tracking": {}
  "/payment-failure": {}
  "/privacy-policy": {}
  "/product/[slug]": { "slug": string; }
  "/reset-password": {}
  "/returns-refund-policy": {}
  "/search": {}
  "/shipping-policy": {}
  "/signup": {}
  "/stores": {}
  "/terms-and-conditions": {}
  "/women": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
